deployment:
  name: api-api
  replicas: 3
  # image: "ailitik/api_api:1.0.0" 
  containerPort: 3001
  healthCheckPath: "/health"
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 15
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  labels:
    app: "api-api"
  selector:
    matchLabels:
      app: "api-api"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  envFrom:
    configMapName: "api-config"
    secretName: "api-secret"

secret:
  name: "api-secret"
  type: "Opaque"
  data:
    user: "aGVsbG8=" # Base64 for 'hello'
    pass: "d29ybGQ=" # Base64 for 'world'

service:
  name: api-api
  selector:
    app: api-api
  ports:
    protocol: "TCP"
    port: 3001
    targetPort: 3001
  type: "NodePort"

config:
  name: "api-config"
  data:
    PORT: "3001"
    DBPORT: "3306"
    DBHOST: "mysql"
    DB: "kaizen"