- name: Install Docker dependencies 
  ansible.builtin.apt:
    name: 
    - ca-certificates
    - curl
    state: present
    update_cache: yes

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ docker_keyrings_dir }}"
    state: directory
    mode: "{{ docker_keyrings_dir_mode }}"

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: "{{ docker_gpg_key_url }}"
    dest: "{{ docker_gpg_key_dest }}"
    mode: "{{ docker_gpg_key_mode }}"
    force: yes  # Ensures the file is updated if the remote content changes

- name: Add the repository to Apt sources using tee
  ansible.builtin.shell:
    cmd: "{{ docker_repo_add_command }}"

- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes

- name: Ensure group "Docker" exists
  ansible.builtin.group:
    name: "{{ docker_group_name }}"
    state: present

- name: Add the user to the group 'Docker'
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: "{{ docker_group_name }}"
    append: yes

- name: Enable and start Docker services
  ansible.builtin.service:
    name: "{{ docker_service_name }}"
    enabled: true
    state: started