pvc:
  name: "mysql-pvc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "local-path" # Ensure local-path-provisioner is installed

service:
  name: "mysql"
  labels:
    app: "mysql"
  ports:
    - name: "mysql"
      port: 3306
  selector:
    app: "MySQL" # Note: Case-sensitive, might need adjustment based on StatefulSet label

statefulset:
  name: "mysql"
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: "mysql"
  template:
    metadata:
      labels:
        app: "mysql"
    spec:
      containers:
        - name: "mysql"
          # image: mysql:8.0
          ports:
            - containerPort: 3306
              name: "mysql"
          env:
            root_valueFrom:
              secretKeyRef:
                name: "api-secret"
                key: "DBPASS"
            user_valueFrom:
              secretKeyRef:
                name: "api-secret"
                key: "DBUSER"
            pass_valueFrom:
              secretKeyRef:
                name: "api-secret"
                key: "DBPASS"
            db_value: "kaizen"
          volumeMounts:
            - name: "mysql-storage"
              mountPath: "/var/lib/mysql"
      volumes:
        - name: "mysql-storage"
          persistentVolumeClaim:
            claimName: "mysql-pvc"
