apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.name }}
spec:
  serviceName: {{ .Values.statefulset.serviceName }}
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.statefulset.selector.matchLabels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulset.template.metadata.labels.app }}
    spec:
      containers:
        - name: {{ .Values.statefulset.template.spec.containers.name }}
          image: mysql:8.0 # ?
          ports:
            - containerPort: {{ .Values.statefulset.template.spec.containers.ports.containerPort }}
              name: {{ .Values.statefulset.template.spec.containers.ports.name }}
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.statefulset.template.spec.containers.env.root_valueFrom.secretKeyRef.name }}
                key: {{ .Values.statefulset.template.spec.containers.env.root_valueFrom.secretKeyRef.key }}
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.statefulset.template.spec.containers.env.user_valueFrom.secretKeyRef.name }}
                key: {{ .Values.statefulset.template.spec.containers.env.user_valueFrom.secretKeyRef.name }}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.statefulset.template.spec.containers.env.pass_valueFrom.secretKeyRef.name }}
                key: {{ .Values.statefulset.template.spec.containers.env.pass_valueFrom.secretKeyRef.name }}
          - name: MYSQL_DATABASE
            value: {{ .Values.statefulset.template.spec.containers.env.db_value }}
          volumeMounts:
            - name: {{ .Values.statefulset.template.spec.containers.volumeMounts.name }}
              mountPath: {{ .Values.statefulset.template.spec.containers.volumeMounts.mountPath }}
      volumes:
        - name: {{ .Values.statefulset.template.spec.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.statefulset.template.spec.volumes.persistentVolumeClaim.claimName }}