apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.labels.app }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.selector.matchLabels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels.app }}
    spec:
      strategy:
        type: {{ .Values.deployment.strategy.type }}
        rollingUpdate:
          maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
          maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
      containers:
      - name: {{ .Values.deployment.name }}
        image: "ailitik/api_api:1.0.0"
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        envFrom:
        - configMapRef: 
            name: {{ .Values.deployment.envFrom.configMapName }}
        - secretRef:
            name: {{ .Values.deployment.envFrom.secretName }}
        resources:
          requests:
            cpu: {{ .Values.deployment.resources.requests.cpu }}
            memory: {{ .Values.deployment.resources.requests.memory }}
          limits:
            cpu: {{ .Values.deployment.resources.limits.cpu }}
            memory: {{ .Values.deployment.resources.limits.memory }}
        readinessProbe:
          httpGet:
            path: {{ .Values.deployment.healthCheckPath }}
            port: {{ .Values.deployment.containerPort }}
          initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.deployment.healthCheckPath }}
            port: {{ .Values.deployment.containerPort }}
          initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
        # startupProbe:
        #   httpGet:
        #     path: /health
        #     port: 3001
        #   failureThreshold: 30
        #   periodSeconds: 5