apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-api
  labels:
    app: api-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-api
  template:
    metadata:
      labels:
        app: api-api
    spec:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
      containers:
      - name: api-api
        image: ailitik/api_api:1.0.0
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef: 
            name: api-config
        - secretRef:
            name: api-secret
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 15
        # startupProbe:
        #   httpGet:
        #     path: /health
        #     port: 3001
        #   failureThreshold: 30
        #   periodSeconds: 5