apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.service.selector.app }}  # Matches the label of the API deployment
  ports:
    - protocol: {{ .Values.service.ports.protocol }}
      port: {{ .Values.service.ports.port }} 
      targetPort: {{ .Values.service.ports.targetPort }}   # The port the API container is listening to
  type: {{ .Values.service.type }} 