apiVersion: v1
kind: Service
metadata:
  name: api-api 
spec:
  selector:
    app: api-api  # Matches the label of the API deployment
  ports:
    - protocol: TCP
      port: 3001 
      targetPort: 3001  # The port the API container is listening on
  type: NodePort 